### PR TITLE
Security vulnerabilities fix

### PR DESCRIPTION
**Pull request by rhowinespinoza**
Fixes:
1. Fix incorrect end tag
2. Fix infinite request loop
3. Use SERVER_NAME instead of HTTP_HOST to prevent SSRF attack

### CODE REVIEW

**Comment by kornicameister** [comment]
It's been 2 years already so asking if there's a plan to get this merged is rather awkward.
I will though ask @rhowinespinoza ; are you able to point out what needed to happen for 2nd point to occur?

**Comment by rhowinespinoza** [comment]
> It's been 2 years already so asking if there's a plan to get this merged is rather awkward. I will though ask @rhowinespinoza ; are you able to point out what needed to happen for 2nd point to occur?

@kornicameister An HTTP GET request to /js/whichbrowser/?a will cause the server to continuously send HTTP GET requests to itself because the detect url will be /js/whichbrowser/?adetect.php.

**Comment by kornicameister** [comment]
image

I know... :D

**Comment by kornicameister** [comment]
@rhowinespinoza were you able to battle test your solution? Is it a script, test somewhere that you used to find and confirm the fix? I mean, I would like to have it used to verify things on my end but given I am not exactly on friendly terms with PHP (although maybe I don't need to), any help would be appreciated.

**Comment by kornicameister** [comment]
oh, lovely :* thanks @NielsLeenheer

**Pull request merged**
